quarkus.http.port=5001
quarkus.http.host=0.0.0.0

orders.raw-root=/data/raw
orders.azure-storage-connection-string=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
orders.azure-raw-container=raw
